# Generated by Django 2.2.17 on 2021-01-27 19:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0019_auto_20210125_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 29, 19, 59, 39, 192698, tzinfo=utc)),
        ),
    ]
