# Generated by Django 2.2.17 on 2021-01-27 22:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0023_auto_20210128_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 29, 22, 15, 52, 791662, tzinfo=utc)),
        ),
    ]
