# Generated by Django 2.2.17 on 2021-02-02 21:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0027_auto_20210202_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 4, 21, 21, 46, 399727, tzinfo=utc)),
        ),
    ]
