# Generated by Django 2.2.17 on 2021-02-07 21:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0034_auto_20210207_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 9, 21, 6, 9, 231277, tzinfo=utc)),
        ),
    ]
