# Generated by Django 2.2.17 on 2021-02-09 20:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0036_auto_20210208_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 11, 20, 51, 23, 603446, tzinfo=utc)),
        ),
    ]
