# Generated by Django 2.2.17 on 2021-02-09 20:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0037_auto_20210209_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 11, 20, 58, 31, 405660, tzinfo=utc)),
        ),
    ]
