# Generated by Django 2.2.17 on 2021-02-09 21:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0038_auto_20210209_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 11, 21, 14, 14, 57218, tzinfo=utc)),
        ),
    ]
