# Generated by Django 2.2.17 on 2021-02-09 21:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0039_auto_20210210_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 11, 21, 59, 58, 198153, tzinfo=utc)),
        ),
    ]
