# Generated by Django 2.2.17 on 2021-02-09 22:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0040_auto_20210210_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 11, 22, 2, 21, 585036, tzinfo=utc)),
        ),
    ]
