# Generated by Django 2.2.17 on 2021-02-11 20:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0042_auto_20210210_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 13, 20, 0, 15, 684358, tzinfo=utc)),
        ),
    ]
